### ISSUE TITLE
RuntimeError: Failed to parse Dictionary from the input stream.

### ISSUE THREAD

**Issue by lawlict** [staplesinLA/first_com#5]
Hello,
    I try running the denoising program but it seems fail to load the model. Can you give me a hand? My environment is: Ubuntu 16.04, python 3.6, CNTK version=2.7. Error log is shown below.

Processing file: /home/l/denoising_DIHARD18/data/DH_0002.wav, segment: 1/3.
ERROR: Problem encountered while processing file "/home/l/denoising_DIHARD18/data/DH_0002.wav". Skipping. Full error output:
Traceback (most recent call last):
  File "main_denoising.py", line 95, in run
    super(Process, self).run()
  File "/home/l/anaconda3/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "main_denoising.py", line 194, in denoise_wav
    gpu_id)
  File "/home/l/denoising_DIHARD18/decode_model.py", line 68, in decode_model
    model_dnn = load_model(MODELF)
  File "/home/l/anaconda3/lib/python3.6/site-packages/cntk/internal/swig_helper.py", line 69, in wrapper
    result = f(*args, **kwds)
  File "/home/l/anaconda3/lib/python3.6/site-packages/cntk/ops/functions.py", line 1721, in load_model
    return Function.load(model, device, format)
  File "/home/l/anaconda3/lib/python3.6/site-packages/cntk/internal/swig_helper.py", line 69, in wrapper
    result = f(*args, **kwds)
  File "/home/l/anaconda3/lib/python3.6/site-packages/cntk/ops/functions.py", line 1635, in load
    return cntk_py.Function.load(str(model), device, format.value)
RuntimeError: Failed to parse Dictionary from the input stream.

[CALL STACK]
[0x7ff44b946ac9]                                                       + 0x7c5ac9
[0x7ff44bb383d0]    CNTK::operator>>(std::istream&,  CNTK::Dictionary&) + 0xa0
[0x7ff44b94be83]    CNTK::Function::  Load  (std::__cxx11::basic_string<wchar_t,std::char_traits<wchar_t>,std::allocator<wchar_t>> const&,  CNTK::DeviceDescriptor const&,  CNTK::ModelFormat) + 0xa3
[0x7ff44c9188d6]                                                       + 0x1cb8d6
[0x5592001e6ad1]    _PyCFunction_FastCallDict                          + 0x91
[0x55920027667c]                                                       + 0x19e67c
[0x559200298cba]    _PyEval_EvalFrameDefault                           + 0x2fa
[0x559200271459]    PyEval_EvalCodeEx                                  + 0x329
[0x559200272376]                                                       + 0x19a376
[0x5592001e699e]    PyObject_Call                                      + 0x3e
[0x55920029a470]    _PyEval_EvalFrameDefault                           + 0x1ab0
[0x55920026fc26]                                                       + 0x197c26
[0x559200270941]                                                       + 0x198941
[0x559200276755]                                                       + 0x19e755
[0x559200298cba]    _PyEval_EvalFrameDefault                           + 0x2fa
[0x559200271459]    PyEval_EvalCodeEx                                  + 0x329
[0x559200272376]                                                       + 0x19a376
[0x5592001e699e]    PyObject_Call                                      + 0x3e
[0x55920029a470]    _PyEval_EvalFrameDefault                           + 0x1ab0
[0x55920026fc26]                                                       + 0x197c26
[0x559200270941]                                                       + 0x198941
[0x559200276755]                                                       + 0x19e755
[0x559200298cba]    _PyEval_EvalFrameDefault                           + 0x2fa
[0x55920026fa94]                                                       + 0x197a94
[0x559200270941]                                                       + 0x198941
[0x559200276755]                                                       + 0x19e755
[0x559200298cba]    _PyEval_EvalFrameDefault                           + 0x2fa
[0x559200271459]    PyEval_EvalCodeEx                                  + 0x329
[0x559200272376]                                                       + 0x19a376
[0x5592001e699e]    PyObject_Call                                      + 0x3e
[0x55920029a470]    _PyEval_EvalFrameDefault                           + 0x1ab0
[0x55920027070b]                                                       + 0x19870b
[0x559200276755]                                                       + 0x19e755
[0x559200298cba]    _PyEval_EvalFrameDefault                           + 0x2fa
[0x55920026fc26]                                                       + 0x197c26
[0x559200270941]                                                       + 0x198941
[0x559200276755]                                                       + 0x19e755
[0x559200298cba]    _PyEval_EvalFrameDefault                           + 0x2fa
[0x55920027070b]                                                       + 0x19870b
[0x559200276755]                                                       + 0x19e755
[0x559200298cba]    _PyEval_EvalFrameDefault                           + 0x2fa
[0x55920027070b]                                                       + 0x19870b
[0x559200276755]                                                       + 0x19e755
[0x559200298cba]    _PyEval_EvalFrameDefault                           + 0x2fa
[0x559200270d7b]    _PyFunction_FastCallDict                           + 0x11b
[0x5592001e6f5f]    _PyObject_FastCallDict                             + 0x26f
[0x5592001eba03]    _PyObject_Call_Prepend                             + 0x63
[0x5592001e699e]    PyObject_Call                                      + 0x3e
[0x55920024302b]                                                       + 0x16b02b
[0x5592002769b7]                                                       + 0x19e9b7
[0x5592001e6d7b]    _PyObject_FastCallDict                             + 0x8b
[0x5592002767ce]                                                       + 0x19e7ce
[0x559200298cba]    _PyEval_EvalFrameDefault                           + 0x2fa
[0x55920027070b]                                                       + 0x19870b
[0x559200276755]                                                       + 0x19e755
[0x559200298cba]    _PyEval_EvalFrameDefault                           + 0x2fa
[0x55920027070b]                                                       + 0x19870b
[0x559200276755]                                                       + 0x19e755
[0x559200298cba]    _PyEval_EvalFrameDefault                           + 0x2fa
[0x55920027070b]                                                       + 0x19870b
[0x559200276755]                                                       + 0x19e755
[0x559200298cba]    _PyEval_EvalFrameDefault                           + 0x2fa
[0x55920026fa94]                                                       + 0x197a94
[0x559200270941]                                                       + 0x198941
[0x559200276755]                                                       + 0x19e755
[0x559200299a7a]    _PyEval_EvalFrameDefault                           + 0x10ba
[0x55920027070b]                                                       + 0x19870b
[0x559200276755]                                                       + 0x19e755
[0x559200298cba]    _PyEval_EvalFrameDefault                           + 0x2fa
[0x559200271459]    PyEval_EvalCodeEx                                  + 0x329
[0x5592002721ec]    PyEval_EvalCode                                    + 0x1c
[0x5592002ec9a4]                                                       + 0x2149a4
[0x5592002ecda1]    PyRun_FileExFlags                                  + 0xa1
[0x5592002ecfa4]    PyRun_SimpleFileExFlags                            + 0x1c4
[0x5592002f0a9e]    Py_Main                                            + 0x63e
[0x5592001b84be]    main                                               + 0xee
[0x7ff461639830]    __libc_start_main                                  + 0xf0
[0x55920029f773]                                                       + 0x1c7773

**Comment by lawlict** [comment]
Em... I get it. I directly clone it down instead of using command 
"git lfs clone https://github.com/staplesinLA/denoising_DIHARD18.git".
