### ISSUE TITLE
 Error while processing file

### ISSUE THREAD

**Issue by asrcomm** [staplesinLA/first_com#9]
Hi, I am find finding error in processing the file.

Processing file: /home/denoising_DIHARD18-master/data/inp1.wav, segment: 1/1.
ERROR: Problem encountered while processing file "/home/denoising_DIHARD18-master/data/inp1.wav". Skipping. Full error output:
Traceback (most recent call last):
  File "main_denoising.py", line 95, in run
    super(Process, self).run()
  File "/usr/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/denoising_DIHARD18-master/decode_model.py", line 68, in decode_model
    model_dnn = load_model(MODELF)
  File "/usr/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/.local/share/virtualenvs/env/lib/python3.5/site-packages/wurlitzer.py", line 307, in pipes
    yield stdout_r, stderr_r
  File "/home/denoising_DIHARD18-master/decode_model.py", line 68, in decode_model
    model_dnn = load_model(MODELF)
  File "/home/.local/share/virtualenvs/env/lib/python3.5/site-packages/cntk/internal/swig_helper.py", line 69, in wrapper
    result = f(*args, **kwds)
  File "/home/.local/share/virtualenvs/env/lib/python3.5/site-packages/cntk/ops/functions.py", line 1721, in load_model
    return Function.load(model, device, format)
  File "/home/.local/share/virtualenvs/env/lib/python3.5/site-packages/cntk/internal/swig_helper.py", line 69, in wrapper
    result = f(*args, **kwds)
  File "/home/.local/share/virtualenvs/env/lib/python3.5/site-packages/cntk/ops/functions.py", line 1635, in load
    return cntk_py.Function.load(str(model), device, format.value)
RuntimeError: Failed to parse Dictionary from the input stream.

**Comment by ablaw123** [comment]
I am having the same issue.  It seems as if the model is corrupted and not loading properly.  Any thoughts on how to fix?

**Comment by lizolson** [comment]
Also having this problem, and not sure if it's a model issue or dependencies problem.

**Comment by jardnzm** [comment]
I have the same issue and I fixed it by wget the model link again in the model directory.  seems like git clone wouldn't download the whole model.

**Comment by jsdtwry** [comment]
@ZimingY Same problem I met. Could you share the model download link for me to get by wget？ I saw your another issue about this and try git lfs did not work either. Thanks!!!
